### PR TITLE
Zafar1

### PR DESCRIPTION
**Pull request by zahmed9**
Loop up of Shower and Cherenkov in THcHodoscope::Setup
If calorimeter and cherenkov is not added to SOS or HMS then it prints a warning message and does not calcualte the efficiency for that spectrometer.

Minimm value of normalized energy and minum value of number of cherenkov photo electrons is added to parameter files for the calculation of tracking efficiency.

NCerNPE and fNormETot be optional parameters When there is not the  !fChern || !fShower and instead just
not increment the counter. cer_npe and normalized_energy_tot are optional 

Changed the name of two global varialble of hodoscope

### CODE REVIEW

**Comment by MarkKJones** [comment]
I downloaded the commit and it does not compile.

src/THcHodoscope.cxx:463: error: 'fNCerNPE' was not declared in this scope
src/THcHodoscope.cxx:464: error: 'fNormETot' was not declared in this scope
src/THcHodoscope.cxx:466: error: too many initializers for 'DBRequest'
src/THcHodoscope.cxx:466: error: too many initializers for 'DBRequest'
src/THcHodoscope.cxx: In member function 'virtual Int_t THcHodoscope::FineProcess(TClonesArray&)':
src/THcHodoscope.cxx:1521: error: 'fNormETot' was not declared in this scope
src/THcHodoscope.cxx:1522: error: 'fNCerNPE' was not declared in this scope
src/THcHodoscope.cxx:1525: error: 'fNormETot' was not declared in this scope
src/THcHodoscope.cxx:1526: error: 'fNCerNPE' was not declared in this scope
scons: *** [src/THcHodoscope.os] Error 1
scons: building terminated because of errors.


 I think that the THcHodoscope.h file needs to be committed. That file must have the new members.

**Comment by zahmed9** [comment]
Hi Mark,
Please check now, I committed the THcHodoscope.h file

**Comment by MarkKJones** [comment]
I am checking now

**Comment by MarkKJones** [comment]
Ok the code compiles and I ran it under hcana_replay fine.
There is a compiler warning about 
src/THcHodoscope.cxx:755: warning: 'fNfpTime' may be used uninitialized in this function
I see that line 783 is commented out
    //      Int_t fNfpTime = 0;
Is there a reason for this? If not uncomment the line and commit src/THcHodoscope.cxx

**Comment by zahmed9** [comment]
I dont know why I did it, I uncommented the line.

**Comment by MarkKJones** [comment]
At line 755,  can you remove fNfpTime from the list of variables being declared as Double_t?

**Comment by zahmed9** [comment]
Just did it, sorry for small bugs, have a good weekend :-)

**Pull request merged**
