### PR TITLE
Zafar1

### PR DESCRIPTION
**Pull request by zahmed9**
Beta no track and chi square of beta no track is added.
cut_replay_both.def and report.template files are modified to include different efficiencies.

### CODE REVIEW

**Comment by MarkKJones** [comment]
There is no betap in DefineVariables for THcHodoscope.cxx which is needed by 
BHMSScinShoulde  cuts_replay_both.def

**Comment by zahmed9** [comment]
Sorry, I forgot to push the changes. Please check now.

**Comment by zahmed9** [comment]
One more thing, I sent THaGoldentrack.h and THaGoldentrack.C to Ole and Steve in which I added beta to golden track.

**Comment by MarkKJones** [comment]
Looks ok now.

**Pull request merged**
