### PR TITLE
New set of classes for trigger data.

### PR DESCRIPTION
**Pull request by JureBericic**
Wrote a new set of classes meant to hold and process trigger data. It is not yet finished, but it works.

### CODE REVIEW

**Comment by JureBericic** [comment]
Shouldn't the build be against root v6 and gcc4.8+ (std=c++11)?

**Comment by sawjlab** [comment]
The counting house machines are still 4.4.7.

**Comment by sawjlab** [comment]
Perhaps use ROOTs string manipulation such as Form instead of std::to_string.

**Comment by sawjlab** [comment]
This request in develop as of commit 388e416b07e127aa00bfa5bb76afcce5ef0d0bee.  Some commits were collapsed and it was rebased onto develop.  The new classes were added to the Makefile so that make as well as scons should work.

**Pull request closed without merging**
