### PR TITLE
Update SCons setup to match podd setup

### PR DESCRIPTION
**Pull request by sawjlab**
I reworked the hcana SCons setup to match some of the changes and simplification that Ole did to the podd SCons setup recently.  Furthermore, all traces of evio are removed from the SCons stuff as the podd build seems to take care of evio for us.   Since I am not really a SCons expert, I would apprecaite if Ed and/or Ole could take a look at this and if others could test this before merging.

One irritant is that any .pyc need to be removed before scons will work.  configure.pyc is the main issue as site_scons/configure.py has stuff that the previous configure.py didn't have.

### CODE REVIEW

**Comment by hansenjo** [comment]
Thanks Steve. I'll take a look. Ed should too.

> 
> One irritant is that any .pyc need to be removed before scons will work.
> configure.pyc is the main issue as site_scons/configure.py has stuff
> that the previous configure.py didn't have.
> 

I ran into that problem as well. You get completely unexpected Python
crashes sometimes unless you clean up the *.pyc files first.

Unfortunately, these files are created by Python itself, not by the
build system. I don't know what would happen if we asked SCons to clean
them since it would be deleting the code it is currently running. We
might end up with one of those "undefined behavior" situations.
Hopefully, the build system will stabilize again soon and this won't be
a persistent problem.

Ole

**Comment by brash99** [comment]
Hi all,

Very nice … I was starting to work on a similar thing myself, but Steve beat me to it (and not unsurprisingly in a slicker way I might add).

I have two comments:  first, the now infamous segfault issue reappears in hcana … and the culprit is again that the -fPIC is not being added to the compilation of src/main.C.  So, one needs to add -fPIC to the CXXFLAGS definitions in the site_scons/linux64.py, site_scons/linux32.py, and site_scons/darwin64.py files.

Second, my original thought when I was looking at this was that we should be able to just use the podd/site_scons/*.py files for configuration, etc., yes?  One would just have to make the appropriate line (that defines the tool path) in the hcana SConstruct read:

baseenv = Environment(ENV = os.environ,tools=["default"],toolpath=[‘podd/site_scons’])

I note that currently, there are differences between the hcana versions and the podd versions of these configuration files.  It would take me some time to figure out if they are substantive differences, or just historical.

Cheers,
E.

> On Oct 6, 2017, at 12:04 PM, Ole Hansen <notifications@github.com> wrote:
> 
> Thanks Steve. I'll take a look. Ed should too.
> 
> > 
> > One irritant is that any .pyc need to be removed before scons will work.
> > configure.pyc is the main issue as site_scons/configure.py has stuff
> > that the previous configure.py didn't have.
> > 
> 
> I ran into that problem as well. You get completely unexpected Python
> crashes sometimes unless you clean up the *.pyc files first.
> 
> Unfortunately, these files are created by Python itself, not by the
> build system. I don't know what would happen if we asked SCons to clean
> them since it would be deleting the code it is currently running. We
> might end up with one of those "undefined behavior" situations.
> Hopefully, the build system will stabilize again soon and this won't be
> a persistent problem.
> 
> Ole
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JeffersonLab_hcana_pull_265-23issuecomment-2D334798566&d=DwMFaQ&c=lz9TcOasaINaaC3U7FbMev2lsutwpI4--09aP8Lu18s&r=QQI4wgZ48DvzGull4QAPAA&m=omZqyKkyRT20XMyH4UziaH1i_IhHxkEbxeprlld6gP8&s=el5GSv5pMB7Ihk1YrTkvgHlPSLeZLSZn6ox6aG8zEkI&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AE1Pu8lv8B7PGRKrnR3R-5FI51dLe9i1gaks5spk-2DVgaJpZM4PwsJh&d=DwMFaQ&c=lz9TcOasaINaaC3U7FbMev2lsutwpI4--09aP8Lu18s&r=QQI4wgZ48DvzGull4QAPAA&m=omZqyKkyRT20XMyH4UziaH1i_IhHxkEbxeprlld6gP8&s=OP3lQ-mFdL_vDqrAmtzep-gtdQ34Q49zjo9HjvTWdYM&e=>.
> 

Dr. Edward J. Brash

Professor of Physics - Christopher Newport University
Staff Scientist - Thomas Jefferson National Accelerator Facility
Honorary Senior Research Fellow - University of Glasgow
Office:	757-594-7451
Mobile:	757-753-2831
FAX:		757-594-7919

**Comment by hansenjo** [comment]
On 10/06/2017 12:51 PM, brash99 wrote:
> 
> I have two comments: first, the now infamous segfault issue reappears in
> hcana … and the culprit is again that the -fPIC is not being added to
> the compilation of src/main.C. So, one needs to add -fPIC to the
> CXXFLAGS definitions in the site_scons/linux64.py,
> site_scons/linux32.py, and site_scons/darwin64.py files.

Ah, good find.

> Second, my original thought when I was looking at this was that we
> should be able to just use the podd/site_scons/*.py files for
> configuration, etc., yes? One would just have to make the appropriate
> line (that defines the tool path) in the hcana SConstruct read:
> 
> baseenv = Environment(ENV =
> os.environ,tools=["default"],toolpath=[‘podd/site_scons’])

Yes, I was thinking the exact same thing.

I discovered one more problem. If EVIO is linked in from an external
source (i.e. $CODA is set or similar and contains an EVIO installation),
then hcana fails to link because EVIO_LIB is not on the link line. We
need to run FindEVIO in hcana's SConstruct, but in a mode where it
doesn't build EVIO (since Podd will do that if necessary) _and_ doesn't
exit if EVIO isn't found (since Podd will build it then). There is
already a flag to make the first condition apply, and I'll have to add
one for the second.

> I note that currently, there are differences between the hcana versions
> and the podd versions of these configuration files. It would take me
> some time to figure out if they are substantive differences, or just
> historical.
> 

It's probably insignificant, but I'll take a peek.

Ole

**Comment by sawjlab** [comment]
On 10/06/2017 12:57 PM, Ole Hansen wrote:
> On 10/06/2017 12:51 PM, brash99 wrote:
>  >
>  > I have two comments: first, the now infamous segfault issue reappears in
>  > hcana … and the culprit is again that the -fPIC is not being added to
>  > the compilation of src/main.C. So, one needs to add -fPIC to the
>  > CXXFLAGS definitions in the site_scons/linux64.py,
>  > site_scons/linux32.py, and site_scons/darwin64.py files.
> 
> Ah, good find.
I'll add that.

> 
>  > Second, my original thought when I was looking at this was that we
>  > should be able to just use the podd/site_scons/*.py files for
>  > configuration, etc., yes? One would just have to make the appropriate
>  > line (that defines the tool path) in the hcana SConstruct read:
>  >
>  > baseenv = Environment(ENV =
>  > os.environ,tools=["default"],toolpath=[‘podd/site_scons’])
> 
> Yes, I was thinking the exact same thing.
I wonder if that would work for the configure.py as I am guessing that 
gets loaded because of the "import configure" in SConstruct and 
site_scons is a place that scons looks.

One thought I had was to have hcana's site_scons contents to mostly be 
soft links.  Or put some magic into SConstruct before the "import 
configure" line.

Should we be using site_scons/site_init.py??

> 
> I discovered one more problem. If EVIO is linked in from an external
> source (i.e. $CODA is set or similar and contains an EVIO installation),
> then hcana fails to link because EVIO_LIB is not on the link line. We
> need to run FindEVIO in hcana's SConstruct, but in a mode where it
> doesn't build EVIO (since Podd will do that if necessary) _and_ doesn't
> exit if EVIO isn't found (since Podd will build it then). There is
> already a flag to make the first condition apply, and I'll have to add
> one for the second.
I'll wait for that.

**Comment by sawjlab** [comment]
Rebased a bit and merged to develop.  (Commit 1ac1ef739e4a460b3c872c0ca3aa29779e7c55db).

I you have any problems building with scons, do

rm *.pyc podd/*.pyc

**Pull request closed without merging**
