### PR TITLE
Add SHMS calorimeter calibration code.

### PR DESCRIPTION
**Pull request by vardant**
Adapted calibration code for the HMS calorimeter to the SHMS case. Currently works on the simulated data. Checked aganst old Fortran code, produces same set of calibration constants. Should be easy to adapt to the real data from the SHMS in the future.

### CODE REVIEW

**Comment by sawjlab** [comment]
There are a number of new large files in these commits.  (calibrated.d, Canvas.pdf, Pcal_calib.raw_data, Q.d, shms_calib.cal_data, 5.r, 5.root, old_calib.cal_data etc.)  Which of these can be generated by running hcana or the calibration scripts?

**Comment by vardant** [comment]
All the *.d files can be generated by the calibration script. Likewise 
Canvas.pdf, Pcal_calib.raw_data, shms_calib.cal_data, 5.root, 
old_calib.cal_data, new_calibrated.d, all the other pdf files.

I can remove them from the remote repository if necessary.

Regards,
Vardan.

**Comment by sawjlab** [comment]
Please do remove the files that are generated from the repository.  You can put a .gitignore file in hc_cal_calib, or shms_cal_calib and list those files that should not be included in git.

Also, could you consider using a different file type than ".d"? .d files are dependency files created and used by make and are always safe to delete.

**Comment by vardant** [comment]
Done! Removed all generated and unnecessary auxiliary files. Changed .d 
extensions by .deb extensions.

Vardan.

**Comment by sawjlab** [comment]
Collapsed into one commit and added a .gitignore file to hc_cal_calib directory to keep various, temp, output and data files out of the repo.

**Pull request closed without merging**
